-- Generated by `jwc migrate new`. Do not edit.
-- 0001_init
--
-- Phases (migrations.md §4): drop view, schemas and types, tables and
-- columns, data, constraints, indexes, functions and triggers, comments,
-- create view, destructive.

BEGIN;

-- ── 1 · schemas and types ──
CREATE SCHEMA IF NOT EXISTS public;

-- ── 2 · tables and columns ──
CREATE TABLE public.category (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(100) NOT NULL,
    description varchar(255) DEFAULT '' NOT NULL,
    usage_count integer DEFAULT 0 NOT NULL,
    user_id integer NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category__user_id_name UNIQUE (user_id, name)
);
CREATE TABLE public.transaction (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    wallet_id integer NOT NULL,
    category_id integer NOT NULL,
    amount integer NOT NULL,
    is_income boolean NOT NULL,
    description varchar(255) DEFAULT '' NOT NULL,
    user_id integer NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_transaction PRIMARY KEY (id)
);
CREATE TABLE public."user" (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name varchar(120) NOT NULL,
    last_name varchar(120) NOT NULL,
    email varchar(255) NOT NULL,
    password_hash varchar(255) NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user__email UNIQUE (email)
);
CREATE TABLE public.wallet (
    id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id integer NOT NULL,
    name varchar(120) NOT NULL,
    balance integer DEFAULT 0 NOT NULL,
    currency varchar(10) NOT NULL,
    created_at timestamptz DEFAULT now() NOT NULL,
    CONSTRAINT pk_wallet PRIMARY KEY (id)
);

-- ── 3 · data ──
-- jwc:data 0001_init
-- A `0001_init.data.sql` sidecar, if present, is applied here
-- (migrations.md §7.2). It is hand-written and never generated.

-- ── 4 · constraints ──
ALTER TABLE public.category ADD CONSTRAINT fk_category__user_id
    FOREIGN KEY (user_id) REFERENCES public."user" (id)
    ON DELETE CASCADE;
ALTER TABLE public.transaction ADD CONSTRAINT fk_transaction__category_id
    FOREIGN KEY (category_id) REFERENCES public.category (id);
ALTER TABLE public.transaction ADD CONSTRAINT fk_transaction__user_id
    FOREIGN KEY (user_id) REFERENCES public."user" (id)
    ON DELETE CASCADE;
ALTER TABLE public.transaction ADD CONSTRAINT fk_transaction__wallet_id
    FOREIGN KEY (wallet_id) REFERENCES public.wallet (id)
    ON DELETE CASCADE;
ALTER TABLE public.wallet ADD CONSTRAINT fk_wallet__user_id
    FOREIGN KEY (user_id) REFERENCES public."user" (id)
    ON DELETE CASCADE;

-- ── 5 · indexes ──
CREATE INDEX ix_category__user_id_usage_count
    ON public.category (user_id, usage_count);
CREATE INDEX ix_transaction__category_id
    ON public.transaction (category_id);
CREATE INDEX ix_transaction__user_id
    ON public.transaction (user_id);
CREATE INDEX ix_transaction__wallet_id_created_at
    ON public.transaction (wallet_id, created_at);
CREATE INDEX ix_wallet__user_id_created_at
    ON public.wallet (user_id, created_at);

-- ── 7 · comments ──
COMMENT ON COLUMN public.category.usage_count IS 'Bumped on every transaction booked against it, so the list can put
the most-used first without a join.';
COMMENT ON COLUMN public.transaction.category_id IS 'No `on delete cascade`: deleting a category must not erase financial
history. The route refuses instead, with `CategoryInUse`.';
COMMENT ON TABLE public."user" IS 'One account. Email is the login handle.';
COMMENT ON COLUMN public."user".password_hash IS 'Argon2id. Never leaves the database (schema.md §3.1).';
COMMENT ON COLUMN public.wallet.balance IS 'Whole so''m. An integer because the currency has no minor unit in
practice, and because a float has no business here.';

COMMIT;
