-- Generated by `jwc migrate new`. Do not edit.
-- down of 0001_init
--
-- Phases (migrations.md §4): drop view, schemas and types, tables and
-- columns, data, constraints, indexes, functions and triggers, comments,
-- create view, destructive.

BEGIN;

-- ── 9 · destructive ──
DROP TABLE public.transaction;
DROP TABLE public.category;
DROP TABLE public.wallet;
DROP TABLE public."user";

COMMIT;
