-- Generated by jwc (incremental diff)
ALTER TABLE "wallet" ALTER COLUMN "balance" TYPE bigint USING "balance"::bigint;
ALTER TABLE "transaction" ALTER COLUMN "amount" TYPE bigint USING "amount"::bigint;
