-- Generated by jwc (incremental diff)
ALTER TABLE "wallet" ALTER COLUMN "balance" TYPE integer USING "balance"::integer;
ALTER TABLE "transaction" ALTER COLUMN "amount" TYPE integer USING "amount"::integer;
