-- Generated by jwc (incremental diff)
CREATE TABLE IF NOT EXISTS "user" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "first_name" varchar(120) NOT NULL,
    "last_name" varchar(120) NOT NULL,
    "email" varchar(255) NOT NULL,
    "password_hash" varchar(255) NOT NULL,
    "created_at" timestamptz NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("email")
);
CREATE TABLE IF NOT EXISTS "wallet" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" integer NOT NULL,
    "name" varchar(120) NOT NULL,
    "balance" integer NOT NULL,
    "currency" varchar(10) NOT NULL,
    "created_at" timestamptz NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_wallet_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "ix_wallet_user_id" ON "wallet" ("user_id");
CREATE TABLE IF NOT EXISTS "category" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" varchar(100) NOT NULL,
    "description" varchar(255) NOT NULL,
    "usage_count" integer NOT NULL,
    "user_id" integer NOT NULL,
    "created_at" timestamptz NOT NULL,
    PRIMARY KEY ("id"),
    UNIQUE ("user_id", "name"),
    CONSTRAINT "fk_category_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "ix_category_user_id" ON "category" ("user_id");
CREATE TABLE IF NOT EXISTS "transaction" (
    "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "wallet_id" integer NOT NULL,
    "category_id" integer NOT NULL,
    "amount" integer NOT NULL,
    "is_income" boolean NOT NULL,
    "description" varchar(255) NOT NULL,
    "created_at" timestamptz NOT NULL,
    "user_id" integer NOT NULL,
    PRIMARY KEY ("id"),
    CONSTRAINT "fk_transaction_wallet_id" FOREIGN KEY ("wallet_id") REFERENCES "wallet" ("id") ON DELETE CASCADE,
    CONSTRAINT "fk_transaction_category_id" FOREIGN KEY ("category_id") REFERENCES "category" ("id"),
    CONSTRAINT "fk_transaction_user_id" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS "ix_transaction_wallet_id" ON "transaction" ("wallet_id");
CREATE INDEX IF NOT EXISTS "ix_transaction_category_id" ON "transaction" ("category_id");
CREATE INDEX IF NOT EXISTS "ix_transaction_user_id" ON "transaction" ("user_id");
